name: Test SPARQL queries

on:
  schedule:
    - cron: '42 9 * * *'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      # - name: Setup venv
      #   run: python -m venv venv

      # - name: Activate venv
      #   run: . venv/bin/activate

      - name: Install dependencies
        run: poetry install

      - name: pip freeze
        run: pip freeze

      - name: Install pytest
        run: pip install "pytest>=6.2.4"

      - name: Run tests
        run: python -m pytest --disable-warnings
