name: Test SPARQL queries

on:
  schedule:
    - cron: '23 */4 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install "pytest>=6.2.4"

      - name: Run tests
        run: pytest --disable-warnings
