name: Test SPARQL queries

on:
  schedule:
    - cron: '42 9 * * *'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

    -  name: Install pytest
       run: pip install "pytest>=6.2.4"

      - name: Run tests
        run: pytest --disable-warnings
