name: Test SPARQL queries

on:
  schedule:
    - cron: '23 */4 * * *'
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: pytest --disable-warnings
